
def PrintDiffBWCommitsRugged(diff_bw_commit_trees)
  puts "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
  puts "START -> DIff generated by rugged gem => "
  puts diff_bw_commit_trees
  puts diff_bw_commit_trees.patch
  puts "END -> DIff generated by rugged gem => "
  puts "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
end

def PrintDiffBWCommitsRubyGit(diff_bw_commits)
  puts "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
  puts "START -> DIff generated by ruby-git gem => "
  puts diff_bw_commits
  puts "END -> DIff generated by ruby-git gem => "
  puts "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
end
